---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./packages/*/src/__tests__/*"
postMerge:
  pattern: 
    - "./packages/*/src/__tests__/*"
postRun:
     command:
        - yarn --version
version: 1.0
