---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./packages/*/src/__tests__/*.spec.ts"
postMerge:
  pattern: 
    - "./packages/*/src/__tests__/*.spec.ts"
postRun:
     command:
        - yarn --version
configFile: jest.config.js
version: 1.0
