---
framework: jest
preRun:
     command:
        - yarn install
        - yarn bootstrap
        - yarn testonly
preMerge:
  pattern:
    - "./packages/**/src/__tests__/*.ts"
postMerge:
  pattern: 
    - "./packages/**/src/__tests__/*.ts"
postRun:
     command:
        - yarn --version
version: 1.0
