---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "**/__tests__/*.ts"
postMerge:
  pattern: 
    - "**/__tests__/*.ts"
postRun:
     command:
        - yarn --version
configFile: jest.config.js
version: 1.0
